//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int IdPrecription { get; set; }
        public int IdHealthRecord { get; set; }
        public string MedicineName { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Count { get; set; }
        public string UserManual { get; set; }
    }
}
